server:
  port: 9030

spring:
  ai:
    openai:
      chat:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
        api-key: sk-8bdb2db3afe84f73a1668251b786b6a5
#        model: qwen3.7-plus
#        model: glm-5.1
        model: qwen3.6-flash
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
        api-key: ${spring.ai.openai.chat.api-key}
        model: text-embedding-v3
    vectorstore:
      qdrant:
        host: localhost
        port: 6333
        collection-name: sftp_rpa_docs
    mcp:
      server:
        protocol: STREAMABLE
        name: streamable-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This streamable server provides real-time notifications"
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sftp-logs
      username: jianghui
      password: 123456

sa-token:
  token-name: satoken
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

sftp:
  server-port: 7022
  default-home-dir: /home/whatsoeversky/sftp/default/
  docs-path: /home/whatsoeversky/code/sftp-rpa/sftp-rpa-docs
  rsa-host-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCsBBzqA7rbk2nSoGzf1zq8pwcmrlPtKYPelNI1Vnt5wQ63WyMSXjC9his6eAtBumnnEq/Q7o5kYcQQYBjzu1w6VVPhw7K7hMBn0b/vP5qIUP5wjQRgg1lDJ8ZvvvHhafcui56R5EbUzGSahkRLna++1cgbfQV/q+/qrq6LazKrmbHJh1FNO5FQJl6IzUjosgzJcxU+db+odOrmLLVeq/IIcKwDFJfTW+zn3Ob3na2xt2ThfPZZ9X+xjhQcn2skXVLf5d21HzozkhsPEpNhLKAmMEb8gMsw2A09W0M+ZLrUId1EMDWl5y7MKnvcEPC9B5BapAcYK8I44PkW7AG19GfXAgMBAAECggEAHpGai9G+3q+LQkWFI6BNjWIHaM3ZF0/l4ePDmXv1dHUlBtuY13ZKphuWSg00PumAUXKmMPR79IXVQG27cXDt2mX4gqny9NUKFkkVmVBNx4TROrIswXQGJGOIpaoitQLOTQS92MJe/gkWpclPkLqElV7LcWsd04r8F1IUra0Os6TRdam6pCUVg+DcaBjK5zkEppGRtU0XX62dzOIlacl1YwW/PcTwFB44DzNdDH4/fC/5Ze2V0skLA07yT5QpicyFzt/6NmDanIT4qrziaQrocU3grIt7UcZMAuDj7ZgBnbDNoSzzGfdPVISiUVD2CVIHl4LttVPstON8lXp1fxxN+QKBgQDOaXMwHsRiw7WWcQfLCYcyUxlGgnjpBIASUYEvDF1/GA4zBKOhsAMtPfLJmujGDdZn4nmBpfOLWV938D1DV9bLoQfnKaxaelXI5BG9dnz/VU/O9ZyZ+SxVyyNbmvXz3u0BhG1ItGgIogdQ4cYiu83pW6BTpKNXXxwuWSURx2jCfwKBgQDVV0g6gZeZnj9tp1AiyzMTtaPMzYhkGnHGUI1yyDFMbdDBebS4hkakv/wnzmKWR4nHAJizSRWvzOmLKN34lbykjy3GDBF3S5qz4RdtvXblW8ntj2wJcs7FDzgCDHsMgwz6ZA450r9WcDaPAK64zx5PYStkwRQSbQDSgFb00i7+qQKBgQC7eUNJvWgZXDAdx+OQIcNNjfQy+mXfHltESArRNKXmvW6IH/qO7FK2UMGnIq+w0vidujEp9BRTyITRZr394FYS9Ns8tbj5JIutvpfuQSQetNmb27C0mIAQHESs+v3Q1fTln+WyV0j2LlP+vlE7UuAexz3DOpGw1Y2++vCUSU14+QKBgHn3+JdaV62/x0uNiEccHQt7oTYJm5x/ceSLURL6WRT1A5BZYHTOb7zo9eRcHgkExUQ8lxCJDBkB8dNZfe4MzVjXcrfzVlj5pGyKl7Zpx3vBSmTCxmVweb43wTGKqR6yHc1ZPrjYQAPPC6IeJcYKw61mRETKDguqvfma3hwBvlRhAoGBALlU2maGzetRV/ZD9BUgtPc9PzZ5kvEQ6ZB4W/BkcuOfEoGQJ8LBeqa6MKnaTuLjB/vIaBxuPhQGqpSWs0PZ9/lKfbNTO8Tb/wwy7xVRQdmAHW0vOc2Lu4AmDJTKb4JD1LCHzoYlH0iP6wxDejAW+xu0WyKvz068wvwjp3k6I8Uq
  ecdsa-host-key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
    1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQRNz0WUunovps5kXNXI5cYk64MjDtxm
    o+Z0gAmFoDglKa746xfJCpjHLDGNh+3RYcUoMJRERvNX/8vRRxYZTXWnAAAAqPLp5Hby6e
    R2AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE3PRZS6ei+mzmRc
    1cjlxiTrgyMO3Gaj5nSACYWgOCUprvjrF8kKmMcsMY2H7dFhxSgwlERG81f/y9FHFhlNda
    cAAAAgJHFNHG58IK9/ydnAuYem9aMvxSQ1MIV3+5s18Sf6uT4AAAALc2Z0cC1zZXJ2ZXIB
    AgMEBQ==
    -----END OPENSSH PRIVATE KEY-----
  ed25519-host-key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBxpMTmVHJLCfsC0BZppDIlOATxQyBJlJ5T/zy4M3M8twAAAJAUQ912FEPd
    dgAAAAtzc2gtZWQyNTUxOQAAACBxpMTmVHJLCfsC0BZppDIlOATxQyBJlJ5T/zy4M3M8tw
    AAAEAVyg/qe0XtDZVCi2QSVYTyHNfPJsxXI0YcclP6XaeSW3GkxOZUcksJ+wLQFmmkMiU4
    BPFDIEmUnlP/PLgzczy3AAAAC3NmdHAtc2VydmVyAQI=
    -----END OPENSSH PRIVATE KEY-----


management:
  abc: false